# Generated by Django 3.2 on 2021-05-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='dateofbirth',
            field=models.CharField(max_length=255),
        ),
    ]
